Add some Arch Linux building instructions
reswitched/libtransistor pull request #104
Opened 2018-02-15 21:04 UTC by hcorion

2018-02-15 22:29 UTC, DavidBuchanan314 commented
There's an AUR package for `python-lz4`, which might be better use than pip. (Installing packages globally with pip can cause annoying packaging conflicts).

2018-02-15 23:51 UTC, roblabla requested changes

2018-02-15 23:51 UTC, roblabla commented on README.md
> +sudo pip install lz4
This should be sudo pip install -r requirements.txt

2018-02-15 23:51 UTC, roblabla commented on README.md
> +sudo pacman -S llvm lld python python-pyelftools pip squashfs-tools
I would rather the python dependencies are installed through pip.

llvm is not necessary, it should have clang instead.

The "official" list from The Guide: `base-devel python python-pip cmake clang lld`

2018-02-15 23:52 UTC, roblabla commented on README.md
> +sudo pip install lz4
Also, maybe we should suggest `pip install --user` ?

2018-02-16 05:10 UTC, hcorion commented on README.md
> +sudo pacman -S llvm lld python python-pyelftools pip squashfs-tools
llvm is needed for llvm-config

2018-02-19 18:19 UTC, hcorion commented
How's this?

2018-02-20 14:05 UTC, merged